#!/bin/bash

OUT=$1

if [ ! $OUT ]; then
  curl -s  www.strandtheatre.com > play.txt
  grep 'now_playing' ./play.txt | cut -d '>' -f2 |cut -d '<' -f1 | cowsay -f dragon
else
  echo "$OUT" | cowsay -f dragon
fi

echo kthxbai
exit 0
